token = "tvgnpxhfngsdknqub9d8ffecaaef8797" # <- EDIT WITH YOUR_TOKEN
tracking_id = ""
version = '1.0.4'
package_id=29

os ="os"    # ['os','android','windows','linux','mac','ios'] , for 'os' program will try auto-detect
os_name ="os_name"
os_version="os_version"
product="product"


[log]
level = 'INFO'


[server]
host = "https://api.gaganode.com"
